### PR TITLE
added --s3-endpoint-url as default

### PR DESCRIPTION
**Pull request by pinzon**
This fixes the cloudformation package command

### CODE REVIEW

**Comment by whummer** [comment]
LGTM - thanks @pinzon 👍

**Comment by heliomartins** [comment]
This change seems to have broken s3api. Example:
It looks like `--s3-endpoint-url` is not being recognized by the cli.



image

I executed it without having a localstack running, that's why connection refused was thrown by v.0.9.0

**Comment by rodnaph** [comment]
Also seeing this using SNS...

```
awslocal sns create-topic --name topic-name
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --s3-endpoint-url=http://localhost:4566
```

**Comment by whummer** [comment]
Thanks for the pointer @heliomartins @rodnaph . This is now fixed in 847547fa860f2806351569c197b026afd345ae51 - a new version `0.11` has just been released. Please let us know if there are any other issues. Thanks!

**Comment by rodnaph** [comment]
Confirmed this fixes it for my use-case - thanks for the quick reply @whummer 👍

**Comment by heliomartins** [comment]
Hello @whummer - It also fixes for me, thanks for doing it so quickly. 👍

**Comment by paul-uz** [comment]
@whummer I am using 0.14 and I still get `Unknown options: --s3-endpoint-url=http://localhost:4566,--s3-endpoint-url=http:localhost:4566` when trying to run `awslocal cloudformation package ...`

**Pull request merged**
